### ISSUE TITLE
Great open-source code

### ISSUE THREAD

**Issue by TaoRuan-Campus** [jwwthu/GNN4Traffic#2]
Thank you so much for creating such a marvelous repo! I am wondering whether you could provide some suggestions on good open-source code to study the spatial-temporal GNN modeling of traffic data considering you have great experience in this area?

**Comment by jwwthu** [comment]
Hi TaoRuan, if you want to start with the off-the-shelf GNNs designed for traffic/spatial-temporal forecasting, I would suggest you try this work: [pytorch_geometric_temporal](https://github.com/benedekrozemberczki/pytorch_geometric_temporal) with the [paper](https://arxiv.org/abs/2104.07788). Otherwise, if you are familar with Pytorch/Tensorflow, you may want to learn a general GNN framework, e.g., [PyTorch Geometric](https://pytorch-geometric.readthedocs.io/en/latest/), [tf_geometric](https://tf-geometric.readthedocs.io/en/latest/), or [DGL](https://docs.dgl.ai/).

**Comment by TaoRuan-Campus** [comment]
> Hi TaoRuan, if you want to start with the off-the-shelf GNNs designed for traffic/spatial-temporal forecasting, I would suggest you try this work: [pytorch_geometric_temporal](https://github.com/benedekrozemberczki/pytorch_geometric_temporal) with the [paper](https://arxiv.org/abs/2104.07788). Otherwise, if you are familar with Pytorch/Tensorflow, you may want to learn a general GNN framework, e.g., [PyTorch Geometric](https://pytorch-geometric.readthedocs.io/en/latest/), [tf_geometric](https://tf-geometric.readthedocs.io/en/latest/), or [DGL](https://docs.dgl.ai/).

Thank you so much. I will surely look into those frameworks, yet I also would like to ask whether you could provide some suggestions on good complete application projects that I could study and learn how to implement a GNN workflow?

**Comment by jwwthu** [comment]
> Thank you so much. I will surely look into those frameworks, yet I also would like to ask whether you could provide some suggestions on good complete application projects that I could study and learn how to implement a GNN workflow?

You may check the code links with the papers. I'll need to check them later before I can give more specific recommendations.

**Comment by TaoRuan-Campus** [comment]
> > Thank you so much. I will surely look into those frameworks, yet I also would like to ask whether you could provide some suggestions on good complete application projects that I could study and learn how to implement a GNN workflow?
> 
> You may check the code links with the papers. I'll need to check them later before I can give more specific recommendations.

Great! Appreciate your reply
